version: "3.9"

services:
  wp:
    build: ./docker/wp
    container_name: ${PROJECT_NAME}-wp
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      PHP_IDE_CONFIG: "serverName=${PROJECT_NAME}"
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_ENVIRONMENT_TYPE', 'development');
    volumes:
      - wp_core:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      wp:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - wp_core:/var/www/html:ro
      - ./wp-content:/var/www/html/wp-content:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mariadb:11
    container_name: ${PROJECT_NAME}-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-buffer-pool-size=128M
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1' $MYSQL_DATABASE || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: ${PROJECT_NAME}-mail
    ports:
      - "8025:8025"  # UI
      - "1025:1025"  # SMTP

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  node:
    image: node:20-alpine
    container_name: ${PROJECT_NAME}-node
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"  # Vite dev server
      - "3001:3001"  # BrowserSync
    command: sh -c "npm install && npm run dev"
    profiles:
      - dev

volumes:
  db_data:
  wp_core:
  redis_data:
  node_modules:
